name: startingpoint
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
base-image: ghcr.io/ublue-os/silverblue-main
fedora-version: 38

modules:
  - type: script
    run: # commands directly run inside scripts directory
      - ./autorun.sh pre
  
  - from-file: common-packages.yml # paths relative to "config" directory

  - type: script
    run:
      - ./autorun.sh post

  - type: yafti # no need for an enable-disable key, inclusion implicitly enables
    # config: yafti.yml # if not specified, would use a default config
    custom-flatpaks:
      - Celluloid: io.github.celluloid_player.Celluloid
      - Krita: org.kde.krita